FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# nebula

Polls is a simple API allowing consumers to view polls and vote in them.

## Browse assets [/browse]

### Browse assets [POST]

+ Request (application/json)

        {
            "fulltext" : "interview",
            "filters" : {
                "ctime" : ["gt", 1467200000]
                },
            "limit" : 100,
            "page" : 0,
            "result" : "full"
        }

+ Response 200 (application/json)

        {
            "response" : 200,
            "message" : "one asset found in 0.0000001 second",
            "count" : 1,
            "data" : [
                {
                    "id_asset" : 1,
                    "title" : "Interview part 1",
                    "ctime" : 1467184934,
                    "mtime" : 1467220000,
                }
            ]
        }