from .constants import *

file_types = {
    "dv"   : VIDEO,
    "avi"  : VIDEO,
    "mov"  : VIDEO,
    "mpg"  : VIDEO,
    "mpeg" : VIDEO,
    "mp4"  : VIDEO,
    "flv"  : VIDEO,
    "m4v"  : VIDEO,
    "m2t"  : VIDEO,
    "m2v"  : VIDEO,
    "m2p"  : VIDEO,
    "m2ts" : VIDEO,
    "mts"  : VIDEO,
    "mkv"  : VIDEO,
    "3gp"  : VIDEO,
    "vob"  : VIDEO,
    "wmv"  : VIDEO,
    "video": VIDEO,
    "mxf"  : VIDEO,
    "ogv"  : VIDEO,
    "divx" : VIDEO,
    "video": VIDEO,

    "wav"  : AUDIO,
    "aiff" : AUDIO,
    "aif"  : AUDIO,
    "ogg"  : AUDIO,
    "mp3"  : AUDIO,
    "mp2"  : AUDIO,
    "m2a"  : AUDIO,
    "aac"  : AUDIO,
    "flac" : AUDIO,

    "jpg"  : IMAGE,
    "jpeg" : IMAGE,
    "png"  : IMAGE,
    "tga"  : IMAGE,
    "targa": IMAGE,
    "tif"  : IMAGE,
    "tiff" : IMAGE,
    "hdr"  : IMAGE,
    "exr"  : IMAGE,
    "bmp"  : IMAGE,
    "gif"  : IMAGE,
    "psd"  : IMAGE,
    "xcf"  : IMAGE
}
